version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: awokly_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: awokly_db
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
